services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: encyclopedai
      POSTGRES_USER: encyclo_user
      POSTGRES_PASSWORD: encyclo_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
volumes:
  db_data: 